---
development:
  cloud_name: blasco9
  api_key: '264377533945434'
  api_secret: ZQmoOiq0Bi8TgcRDAcLqvwYznQ0
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: blasco9
  api_key: '264377533945434'
  api_secret: ZQmoOiq0Bi8TgcRDAcLqvwYznQ0
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: blasco9
  api_key: '264377533945434'
  api_secret: ZQmoOiq0Bi8TgcRDAcLqvwYznQ0
  enhance_image_tag: true
  static_file_support: false
